version: 2025.12.1
slug: racksync-cloudflare-tunnel-zerotrust
name: "Cloudflare Tunnel Zero Trust"
description: "Cloudflare Tunnel from RACKSYNC.COM with metrics support"
url: https://github.com/racksync/hass-addons-suite/tree/main/zerotrust/
codenotary: devops@racksync.com
ingress: false
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
auth_api: true
boot: auto
host_network: true
apparmor: true
host_pid: false
homeassistant: 2025.10.1
advanced: true
stage: stable
options:
  token: ""
  desc: ""
  config: false
  protocol: "quic"
  no_autoupdate: false
  metrics_enabled: false
  metrics_port: 2025
schema:
  token: str?
  desc: str?
  config: bool?
  protocol: list(http2|quic)?
  no_autoupdate: bool
  metrics_enabled: bool?
  metrics_port: int?