version: 2025.11.1
slug: racksync-cloudflare-tunnel-zerotrust-pi
name: Cloudflare Tunnel Zero Trust for Raspberry Pi 
description: Cloudflare Tunnel from RACKSYNC.COM 
url: https://github.com/racksync/hass-addons-suite/tree/main/zerotrust/zerotrust-pi
codenotary: devops@racksync.com
ingress: false
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
boot: auto
host_network: true
apparmor: true
host_pid: false
homeassistant: 2023.8.1
advanced: true
stage: stable
options:
  token: ""
  desc: ""
  config: false
  flag: ""
  no_autoupdate: false
schema:
  token: str?
  desc: str?
  config: bool?
  flag: str?
  no_autoupdate: bool